# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven package publish and Docker image publish

on:
  push:
    branches:
      - main

jobs:
  maven:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  docker:
    needs: maven
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact from Maven job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: .

      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u mugibor -p ${{ github.token }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/mugibor/cubix/cloudnative/demo:actions

      - name: Push Docker image
        run: docker push ghcr.io/mugibor/cubix/cloudnative/demo:actions